global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    directory: /etc/traefik/dynamic/
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-ssl
          scheme: https
  web-ssl:
    address: ":443"
  postgres:
    address: ":5432"
  mongo:
    address: ":27017"
  electric:
    address: ":65432"
  vite:
    address: ":5173"
