#!/usr/bin/env bash

function print_scaffold {
	local domain=${1}
	if [ -z "${domain}" ]; then
		echo "No domain given. Exiting."
		exit 1
	fi
	local service_name=${2}
	if [ -z "${service_name}" ]; then
		echo "No service_name given. Exiting."
		exit 1
	fi
	local network_name=${3}
	if [ -z "${network_name}" ]; then
		echo "No network_name given. Exiting."
		exit 1
	fi
	local port=${4}
	if [ -z "${port}" ]; then
		port=5432
	fi

	echo "This print contains the Traefik labels and network config for database service in the docker-compose.yaml"
	echo

	cat <<EOF
version: "3.7"
services:
  ...
  ${service_name}:
    ...
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${network_name}"
      - "traefik.tcp.routers.${service_name}.rule=HostSNI(${service_name}.${domain})"
      - "traefik.tcp.routers.${service_name}.entryPoints=postgres"
      - "traefik.tcp.routers.${service_name}.tls=true"
      - "traefik.tcp.service_names.${service_name}-svc.loadbalancer.server.port=${port}"

networks:
  default:
    name: ${network_name}
EOF
}

print_scaffold "${@}"
