#!/usr/bin/env bash

image_name="traefik:v3.0.0-beta3"
container_name="dev_proxy"

set -eu

function start {
	echo "Starting dev-proxy..."
	docker run \
		-d \
		--name ${container_name} \
		--restart="unless-stopped" \
		--security-opt="no-new-privileges=true" \
		--volume="${PWD}/config/base.yml:/etc/traefik/traefik.yml:ro" \
		--volume="${PWD}/config/dynamic:/etc/traefik/dynamic:ro" \
		--volume="${PWD}/certs:/etc/certs:ro" \
		--volume="/var/run/docker.sock:/var/run/docker.sock" \
		--publish="80:80" \
		--publish="443:443" \
		--publish="15432:5432" \
		${image_name} >/dev/null

	if [ -f "networks" ]; then
		echo "Connecting to networks:"
		while read -r network_name; do
			echo "${network_name}"
			docker network connect "${network_name}" "${container_name}"
		done <networks
	fi
}

start
